#pragma once

/* constants */

enum
{
	MAXIMUM_ENVIRONMENT_OBJECT_PALETTE_ENTRIES_PER_STRUCTURE = 100,
	MAXIMUM_ENVIRONMENT_OBJECTS_PER_STRUCTURE = 16384,
	MAXIMUM_MARKERS_PER_STRUCTURE = 1024,
	MAXIMUM_BREAKABLE_SURFACES_PER_STRUCTURE = 8448,
	MAXIMUM_SKIES_PER_SCENARIO = 32,
	k_maximum_instance_geometry_instances_per_cluster = 1024,
	MAXIMUM_CLUSTER_PORTALS_PER_CLUSTER = 512,
	MAXIMUM_DETAIL_OBJECTS_PER_STRUCTURE = 2097152,
	MAXIMUM_DETAIL_OBJECT_CELLS_PER_STRUCTURE = 262144,
	MAXIMUM_DETAIL_OBJECT_LAYERS_PER_STRUCTURE = 32,
	MAXIMUM_DETAIL_OBJECT_COUNT = (MAXIMUM_DETAIL_OBJECT_LAYERS_PER_STRUCTURE * MAXIMUM_DETAIL_OBJECT_CELLS_PER_STRUCTURE),
	MAXIMUM_PLANES_PER_WEATHER_POLYHEDRON = 16,
	MAXIMUM_WEATHER_POLYHEDRA_PER_STRUCTURE = 32,
	MAXIMUM_FOG_PLANES_PER_STRUCTURE = 127,
	MAXIMUM_VERTICES_PER_CLUSTER_PORTAL = 128,
	MAXIMUM_CLUSTER_PORTALS_PER_STRUCTURE = 512,
	MAXIMUM_NODES_PER_BSP3D = 131072,
	MAXIMUM_COLLISION_MATERIALS_PER_STRUCTURE = 512,
	MAXIMUM_FOG_ZONES_PER_STRUCTURE = 127,
};
