#pragma once
#include "halo_playlist_item_collection.h"

#define k_halo_playlist_oddball_property_item_count 12

enum e_halo_playlist_oddball_property : int32
{
	_halo_playlist_oddball_property_score_to_win_round,
	_halo_playlist_oddball_property_team_play,
	_halo_playlist_oddball_property_team_scoring,
	_halo_playlist_oddball_property_team_changing,
	_halo_playlist_oddball_property_force_even_teams,
	_halo_playlist_oddball_property_ball_count,
	_halo_playlist_oddball_property_ball_hit_damage,
	_halo_playlist_oddball_property_speed_with_ball,
	_halo_playlist_oddball_property_toughness_with_ball,
	_halo_playlist_oddball_property_active_camo_with_ball,
	_halo_playlist_oddball_property_vehicle_operation,
	_halo_playlist_oddball_property_ball_indicator,

	k_halo_playlist_oddball_property_count,
	k_halo_playlist_oddball_property_invalid = NONE
};

e_halo_playlist_oddball_property halo_playlist_item_collection_oddball_property_get_value(wchar_t* value);