#pragma once
#include "halo_playlist_item_collection.h"

#define k_halo_playlist_player_property_item_count 9

enum e_halo_playlist_player_property : int32
{
	_halo_playlist_player_property_max_active_players,
	_halo_playlist_player_property_lives_per_round,
	_halo_playlist_player_property_respawn_time,
	_halo_playlist_player_property_suicide_penalty,
	_halo_playlist_player_property_shield_type,
	_halo_playlist_player_property_motion_sensor,
	_halo_playlist_player_property_active_camo,
	_halo_playlist_player_property_extra_damage,
	_halo_playlist_player_property_damage_resistance,

	k_halo_playlist_player_property_count,
	k_halo_playlist_player_property_invalid = NONE
};

e_halo_playlist_player_property halo_playlist_item_collection_player_property_get_value(wchar_t* value);