#pragma once
#include "halo_playlist_item_collection.h"

#define k_halo_playlist_assault_property_item_count 15

enum e_halo_playlist_assault_property : int32
{
	_halo_playlist_assault_property_score_to_win_round,
	_halo_playlist_assault_property_team_changing,
	_halo_playlist_assault_property_force_even_teams,
	_halo_playlist_assault_property_bomb_type,
	_halo_playlist_assault_property_enemy_bomb_indicator,
	_halo_playlist_assault_property_sudden_death,
	_halo_playlist_assault_property_bomb_touch_return,
	_halo_playlist_assault_property_bomb_reset_time,
	_halo_playlist_assault_property_bomb_arm_time,
	_halo_playlist_assault_property_sticky_arming,
	_halo_playlist_assault_property_slow_with_bomb,
	_halo_playlist_assault_property_bomb_hit_damage,
	_halo_playlist_assault_property_damage_resistance_with_bomb,
	_halo_playlist_assault_property_active_camo_with_bomb,
	_halo_playlist_assault_property_vehicle_operation,

	k_halo_playlist_assault_property_count,
	k_halo_playlist_assault_property_invalid = NONE
};

e_halo_playlist_assault_property halo_playlist_item_collection_assault_property_get_value(wchar_t* value);