#pragma once

#define XONLINE_E_STORAGE_FILE_NOT_FOUND 0x8015C004

typedef enum _XSTORAGE_FACILITY
{
	XSTORAGE_FACILITY_GAME_CLIP = 1,
	XSTORAGE_FACILITY_PER_TITLE = 2,
	XSTORAGE_FACILITY_PER_USER_TITLE = 3
} XSTORAGE_FACILITY;

#pragma pack(push, 1)
typedef struct _XSTORAGE_DOWNLOAD_TO_MEMORY_RESULTS {
	DWORD dwBytesTotal;
	XUID xuidOwner;
	FILETIME ftCreated;
} XSTORAGE_DOWNLOAD_TO_MEMORY_RESULTS;
#pragma pack(pop)

