#pragma once

// DLL VERSION
#define DLL_VERSION_MAJOR               0
#define DLL_VERSION_MINOR               6
#define DLL_VERSION_REVISION            8
#define DLL_VERSION_BUILD				1

#define DLL_VERSION            DLL_VERSION_MAJOR, DLL_VERSION_MINOR, DLL_VERSION_REVISION, DLL_VERSION_BUILD

#define _CART_VER_STRINGIFY2(s) #s
#define _CART_VER_STRINGIFY(s) _CART_VER_STRINGIFY2(s)
#define DLL_VERSION_STR _CART_VER_STRINGIFY(DLL_VERSION_MAJOR) "." _CART_VER_STRINGIFY(DLL_VERSION_MINOR) "." _CART_VER_STRINGIFY(DLL_VERSION_REVISION) "." _CART_VER_STRINGIFY(DLL_VERSION_BUILD)
