#pragma once



#ifndef _CARTOGRAPHER_DLL_CONF
// DO NOT USE VERSIONS ABOVE USHORT_MAX - 1 (above 65534) OR BELLOW 0 
// REPLACE THE DEFAULTS FOR BOTH EXECUTABLE_VERSION AND COMPATIBLE_VERSION WITH THE SAME VALUE FOR THE MOST PART
// OR YOU CAN SET THE COMPATIBLE VERSION HIGHER IF YOU WANT TO ALLOW OLDER VERSIONS TO JOIN (EXECUTABLE_VERSION SHOULD NOT BE ABOVE IT)
// ALSO THE VERSION SHOULD BE MODIFIED INCREMENTALLY, NOT RANDOMLY
#define EXECUTABLE_VERSION 11122
#define COMPATIBLE_VERSION 11122

static_assert(EXECUTABLE_VERSION < 65535 && EXECUTABLE_VERSION > 0, "EXECUTABLE_VERSION VALUE EXCEEDS 65534");
static_assert(COMPATIBLE_VERSION < 65535 && COMPATIBLE_VERSION > 0, "COMPATIBLE_VERSION VALUE EXCEEDS 65534");

// DO NOT CHANGE, DO NOT USE TYPES ABOVE 7 OR BELLOW 0 (3 bits values max)
#define EXECUTABLE_TYPE 4
static_assert(EXECUTABLE_TYPE <= 7 && EXECUTABLE_TYPE >= 0, "EXECUTABLE_TYPE VALUE EXCEEDS 7 OR BELLOW 0");
#endif


// DLL VERSION
#define DLL_VERSION_MAJOR               0
#define DLL_VERSION_MINOR               6
#define DLL_VERSION_REVISION            8
#define DLL_VERSION_BUILD				        5

#define DLL_VERSION            DLL_VERSION_MAJOR, DLL_VERSION_MINOR, DLL_VERSION_REVISION, DLL_VERSION_BUILD

#define _CART_VER_STRINGIFY2(s) #s
#define _CART_VER_STRINGIFY(s) _CART_VER_STRINGIFY2(s)
#define DLL_VERSION_STR _CART_VER_STRINGIFY(DLL_VERSION_MAJOR) "." _CART_VER_STRINGIFY(DLL_VERSION_MINOR) "." _CART_VER_STRINGIFY(DLL_VERSION_REVISION) "." _CART_VER_STRINGIFY(DLL_VERSION_BUILD) "\0"
