#pragma once

enum e_input_key_code : int16
{
	_key_left_button = 1,
	_key_right_button,
	_key_cancel,
	_key_mouse_button,
	_key_x_button_1,
	_key_x_button_2,
	
	_key_reserved_7,

	_key_backspace,
	_key_tab,

	_key_reserved_A,
	_key_reserved_B,

	_key_clear,
	_key_return,

	_key_reserved_E,
	_key_reserved_F,

	_key_shift,
	_key_control,
	_key_menu,
	_key_pause,
	_key_caps_lock,
	_key_kana,
	_key_ime_on,
	_key_junja,
	_key_final,
	_key_kanji,
	_key_ime_off,
	_key_escape,
	_key_convert,
	_key_nonconvert,
	_key_accept,
	_key_modechange,
	_key_space,
	_key_page_up,
	_key_page_down,
	_key_end,
	_key_home,
	_key_left_arrow,
	_key_up_arrow,
	_key_right_arrow,
	_key_down_arrow,
	_key_select,
	_key_print,
	_key_execute,
	_key_snapshot,
	_key_insert,
	_key_delete,
	_key_help,
	_key_0,
	_key_1,
	_key_2,
	_key_3,
	_key_4,
	_key_5,
	_key_6,
	_key_7,
	_key_8,
	_key_9,

	_key_reserved_3A,
	_key_reserved_3B,
	_key_reserved_3C,
	_key_reserved_3D,
	_key_reserved_3E,
	_key_reserved_3F,
	_key_reserved_40,

	_key_a,
	_key_b,
	_key_c,
	_key_d,
	_key_e,
	_key_f,
	_key_g,
	_key_h,
	_key_i,
	_key_j,
	_key_k,
	_key_l,
	_key_m,
	_key_n,
	_key_o,
	_key_p,
	_key_q,
	_key_r,
	_key_s,
	_key_t,
	_key_u,
	_key_v,
	_key_w,
	_key_x,
	_key_y,
	_key_z,
	_key_left_windows,
	_key_right_windows,
	_key_application,

	_key_reserved_5E,	// VK key of 0x5E is reserved

	_key_sleep,
	_keypad_0,
	_keypad_1,
	_keypad_2,
	_keypad_3,
	_keypad_4,
	_keypad_5,
	_keypad_6,
	_keypad_7,
	_keypad_8,
	_keypad_9,
	_keypad_multiply,
	_keypad_add,
	_keypad_separator,
	_keypad_subtract,
	_keypad_decimal,
	_keypad_divide,

	_key_f1,
	_key_f2,
	_key_f3,
	_key_f4,
	_key_f5,
	_key_f6,
	_key_f7,
	_key_f8,
	_key_f9,
	_key_f10,
	_key_f11,
	_key_f12,
	_key_f13,
	_key_f14,
	_key_f15,
	_key_f16,
	_key_f17,
	_key_f18,
	_key_f19,
	_key_f20,
	_key_f21,
	_key_f22,
	_key_f23,
	_key_f24,

	_key_reserved_88,
	_key_reserved_89,
	_key_reserved_8A,
	_key_reserved_8B,
	_key_reserved_8C,
	_key_reserved_8D,
	_key_reserved_8E,
	_key_reserved_8F,

	_keypad_num_lock,
	_key_scroll_lock,
	
	_keypad_nec_equal,	// NEC PC-9800 kbd definitions
	
	_key_dictionary = _keypad_nec_equal,
	_key_unregister_word,
	_key_register_word,
	_key_left_oyayubi,
	_key_right_oyayubi,

	_key_reserved_97,
	_key_reserved_98,
	_key_reserved_99,
	_key_reserved_9A,
	_key_reserved_9B,
	_key_reserved_9C,
	_key_reserved_9D,
	_key_reserved_9E,
	_key_reserved_9F,

	_key_left_shift,
	_key_right_shift,
	_key_left_control,
	_key_right_control,
	_key_left_alt,
	_key_right_alt,

	_key_browser_back,
	_key_browser_forward,
	_key_browser_refresh,
	_key_browser_stop,
	_key_browser_search,
	_key_browser_favorites,
	_key_browser_home,

	_key_volume_mute,
	_key_volume_down,
	_key_volume_up,

	_key_media_next_track,
	_key_media_prev_track,
	_key_media_stop,
	_key_media_play_pause,

	_key_launch_mail,
	_key_launch_media_select,
	_key_launch_app1,
	_key_launch_app2,

	_key_reserved_B8,
	_key_reserved_B9,

	_key_oem_1,
	_key_oem_plus,
	_key_oem_comma,
	_key_oem_minus,
	_key_oem_period,
	_key_oem_2,
	_key_oem_3,

	_key_reserved_C1,
	_key_reserved_C2,
	_key_reserved_C3,
	_key_reserved_C4,
	_key_reserved_C5,
	_key_reserved_C6,
	_key_reserved_C7,
	_key_reserved_C8,
	_key_reserved_C9,
	_key_reserved_CA,
	_key_reserved_CB,
	_key_reserved_CC,
	_key_reserved_CD,
	_key_reserved_CE,
	_key_reserved_CF,
	_key_reserved_D0,
	_key_reserved_D1,
	_key_reserved_D2,
	_key_reserved_D3,
	_key_reserved_D4,
	_key_reserved_D5,
	_key_reserved_D6,
	_key_reserved_D7,
	_key_reserved_D8,
	_key_reserved_D9,
	_key_reserved_DA,

	_key_oem_4,
	_key_oem_5,
	_key_oem_6,
	_key_oem_7,
	_key_oem_8,

	_key_reserved_E0,

	_key_oem_ax,
	_key_oem_102,
	_key_ico_help,
	_key_ico_00,
	_key_process_key,
	_key_ico_clear,
	_key_packet,

	_key_reserved_E8,

	_key_oem_reset,
	_key_oem_jump,
	_key_oem_pa1,
	_key_oem_pa2,
	_key_oem_pa3,
	_key_oem_wsctrl,

	_key_oem_cusel,
	_key_oem_attn,
	_key_oem_finish,
	_key_oem_copy,
	_key_oem_auto,
	_key_oem_enlw,
	_key_oem_backtab,

	_key_attn,
	_key_crsel,
	_key_exsel,
	_key_ereof,
	_key_play,
	_key_zoom,
	_key_noname,
	_key_pa1,
	_key_oem_clear,
	
	_key_not_a_key,
	NUMBER_OF_KEYS,

	_keypad_left_shift = 257,
	_keypad_left_control,
	_keypad_left_windows,
	_keypad_left_menu,

	_keypad_unk_261 = 261,
	_keypad_enter = 262,

	/* Below are keys that don't have a VK key code that we resolve at runtime */

	FIRST_REMAPPED_KEY,
	_key_tilde = FIRST_REMAPPED_KEY,
	_key_subtract,
	_key_left_square_bracket,
	_key_right_square_bracket,
	_key_backslash,
	_key_semicolon,
	_key_apostrophe,
	_key_comma,
	_key_period,
	_key_forwardslash,
	_key_equal,
	_key_add,
	_key_circumflex_accent,
	_key_dollar_sign,
	_key_asterisk,
	_key_colon,
	_key_exclamation_mark,
	_key_ampersand,
	_key_quotation_mark,
	_key_u_umlaut,			// ü
	_key_o_umlaut,			// ö
	_key_a_umalut,			// ä
	_key_eszett,			// ß
	_key_u_accent_grave,	// ù
	_key_ene,				// ñ
	_key_acute_accent,		// ´
	_key_e_grave,			// è
	_key_o_grave,			// ò
	_key_a_grave,			// à
	_key_c_cedilla,			// ç
	LAST_REMAPPED_KEY,

	REMAPPED_KEY_COUNT = LAST_REMAPPED_KEY - FIRST_REMAPPED_KEY,
};
