#pragma once

enum e_damage_reporting_type : short
{
	damage_reporting_type_guardians = 0,
	damage_reporting_type_falling_damage = 1,
	damage_reporting_type_generic_collision_damage = 2,
	damage_reporting_type_generic_melee_damage = 3,
	damage_reporting_type_generic_explosion = 4,
	damage_reporting_type_magnum_pistol = 5,
	damage_reporting_type_plasma_pistol = 6,
	damage_reporting_type_needler = 7,
	damage_reporting_type_smg = 8,
	damage_reporting_type_plasma_rifle = 9,
	damage_reporting_type_battle_rifle = 10,
	damage_reporting_type_carbine = 11,
	damage_reporting_type_shotgun = 12,
	damage_reporting_type_sniper_rifle = 13,
	damage_reporting_type_beam_rifle = 14,
	damage_reporting_type_rocket_launcher = 15,
	damage_reporting_type_flak_cannon = 16,
	damage_reporting_type_brute_shot = 17,
	damage_reporting_type_disintegrator = 18,
	damage_reporting_type_brute_plasma_rifle = 19,
	damage_reporting_type_energy_sword = 20,
	damage_reporting_type_frag_grenade = 21,
	damage_reporting_type_plasma_grenade = 22,
	damage_reporting_type_flag_melee_damage = 23,
	damage_reporting_type_bomb_melee_damage = 24,
	damage_reporting_type_bomb_explosion_damage = 25,
	damage_reporting_type_ball_melee_damage = 26,
	damage_reporting_type_human_turret = 27,
	damage_reporting_type_plasma_turret = 28,
	damage_reporting_type_banshee = 29,
	damage_reporting_type_ghost = 30,
	damage_reporting_type_mongoose = 31,
	damage_reporting_type_scorpion = 32,
	damage_reporting_type_spectre_driver = 33,
	damage_reporting_type_spectre_gunner = 34,
	damage_reporting_type_warthog_driver = 35,
	damage_reporting_type_warthog_gunner = 36,
	damage_reporting_type_wraith = 37,
	damage_reporting_type_tank = 38,
	damage_reporting_type_sentinel_beam = 39,
	damage_reporting_type_sentinel_rpg = 40,
	damage_reporting_type_teleporter = 41
};