#pragma once
namespace ControllerInput
{
	struct CustomControllerLayout
	{
		WORD DPAD_UP		= XINPUT_GAMEPAD_DPAD_UP;
		WORD DPAD_DOWN		= XINPUT_GAMEPAD_DPAD_DOWN;
		WORD DPAD_LEFT		= XINPUT_GAMEPAD_DPAD_LEFT;
		WORD DPAD_RIGHT		= XINPUT_GAMEPAD_DPAD_RIGHT;
		WORD START			= XINPUT_GAMEPAD_START;
		WORD BACK			= XINPUT_GAMEPAD_BACK;
		WORD LEFT_THUMB		= XINPUT_GAMEPAD_LEFT_THUMB;
		WORD RIGHT_THUMB	= XINPUT_GAMEPAD_RIGHT_THUMB;
		WORD LEFT_SHOULDER	= XINPUT_GAMEPAD_LEFT_SHOULDER;
		WORD RIGHT_SHOULDER	= XINPUT_GAMEPAD_RIGHT_SHOULDER;
		WORD A				= XINPUT_GAMEPAD_A;
		WORD B				= XINPUT_GAMEPAD_B;
		WORD X				= XINPUT_GAMEPAD_X;
		WORD Y				= XINPUT_GAMEPAD_Y;
		void ToArray(WORD* out)
		{
			WORD temp[] = { DPAD_UP , DPAD_DOWN , DPAD_LEFT, DPAD_RIGHT, START, BACK, LEFT_THUMB, RIGHT_THUMB, LEFT_SHOULDER, RIGHT_SHOULDER, A, B ,X, Y };
			memcpy(out, temp, sizeof(temp));
		}
	};
}