#include "stdafx.h"
#include "ControllerInput.h"

ControllerInput::CustomControllerLayout::CustomControllerLayout(void)
{
	DPAD_UP = XINPUT_GAMEPAD_DPAD_UP;
	DPAD_DOWN = XINPUT_GAMEPAD_DPAD_DOWN;
	DPAD_LEFT = XINPUT_GAMEPAD_DPAD_LEFT;
	DPAD_RIGHT = XINPUT_GAMEPAD_DPAD_RIGHT;
	START = XINPUT_GAMEPAD_START;
	BACK = XINPUT_GAMEPAD_BACK;
	LEFT_THUMB = XINPUT_GAMEPAD_LEFT_THUMB;
	RIGHT_THUMB = XINPUT_GAMEPAD_RIGHT_THUMB;
	LEFT_SHOULDER = XINPUT_GAMEPAD_LEFT_SHOULDER;
	RIGHT_SHOULDER = XINPUT_GAMEPAD_RIGHT_SHOULDER;
	A = XINPUT_GAMEPAD_A;
	B = XINPUT_GAMEPAD_B;
	X = XINPUT_GAMEPAD_X;
	Y = XINPUT_GAMEPAD_Y;
	return;
}
