// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: h2mod.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "h2mod.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* H2ModPacket_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  H2ModPacket_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* H2ModPacket_Type_descriptor_ = NULL;
const ::google::protobuf::Descriptor* h2mod_set_grenade_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  h2mod_set_grenade_reflection_ = NULL;
const ::google::protobuf::Descriptor* h2mod_set_team_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  h2mod_set_team_reflection_ = NULL;
const ::google::protobuf::Descriptor* h2mod_map_info_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  h2mod_map_info_reflection_ = NULL;
const ::google::protobuf::Descriptor* h2mod_lobby_settings_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  h2mod_lobby_settings_reflection_ = NULL;
const ::google::protobuf::Descriptor* StringMap_FieldEntry_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StringMap_FieldEntry_reflection_ = NULL;
const ::google::protobuf::Descriptor* h2mod_map_checksum_state_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  h2mod_map_checksum_state_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_h2mod_2eproto() {
  protobuf_AddDesc_h2mod_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "h2mod.proto");
  GOOGLE_CHECK(file != NULL);
  H2ModPacket_descriptor_ = file->message_type(0);
  static const int H2ModPacket_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(H2ModPacket, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(H2ModPacket, h2_set_player_team_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(H2ModPacket, set_grenade_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(H2ModPacket, map_info_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(H2ModPacket, lobby_settings_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(H2ModPacket, checksum_),
  };
  H2ModPacket_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      H2ModPacket_descriptor_,
      H2ModPacket::default_instance_,
      H2ModPacket_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(H2ModPacket, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(H2ModPacket, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(H2ModPacket));
  H2ModPacket_Type_descriptor_ = H2ModPacket_descriptor_->enum_type(0);
  h2mod_set_grenade_descriptor_ = file->message_type(1);
  static const int h2mod_set_grenade_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_set_grenade, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_set_grenade, count_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_set_grenade, pindex_),
  };
  h2mod_set_grenade_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      h2mod_set_grenade_descriptor_,
      h2mod_set_grenade::default_instance_,
      h2mod_set_grenade_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_set_grenade, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_set_grenade, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(h2mod_set_grenade));
  h2mod_set_team_descriptor_ = file->message_type(2);
  static const int h2mod_set_team_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_set_team, peerindex_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_set_team, team_),
  };
  h2mod_set_team_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      h2mod_set_team_descriptor_,
      h2mod_set_team::default_instance_,
      h2mod_set_team_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_set_team, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_set_team, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(h2mod_set_team));
  h2mod_map_info_descriptor_ = file->message_type(3);
  static const int h2mod_map_info_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_map_info, mapfilename_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_map_info, mapsize_),
  };
  h2mod_map_info_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      h2mod_map_info_descriptor_,
      h2mod_map_info::default_instance_,
      h2mod_map_info_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_map_info, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_map_info, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(h2mod_map_info));
  h2mod_lobby_settings_descriptor_ = file->message_type(4);
  static const int h2mod_lobby_settings_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_lobby_settings, mp_explosion_physics_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_lobby_settings, mp_sputnik_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_lobby_settings, mp_grunt_bday_party_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_lobby_settings, grenade_chain_react_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_lobby_settings, banshee_bomb_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_lobby_settings, mp_blind_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_lobby_settings, flashlight_),
  };
  h2mod_lobby_settings_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      h2mod_lobby_settings_descriptor_,
      h2mod_lobby_settings::default_instance_,
      h2mod_lobby_settings_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_lobby_settings, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_lobby_settings, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(h2mod_lobby_settings));
  StringMap_FieldEntry_descriptor_ = file->message_type(5);
  static const int StringMap_FieldEntry_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StringMap_FieldEntry, key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StringMap_FieldEntry, value_),
  };
  StringMap_FieldEntry_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      StringMap_FieldEntry_descriptor_,
      StringMap_FieldEntry::default_instance_,
      StringMap_FieldEntry_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StringMap_FieldEntry, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StringMap_FieldEntry, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(StringMap_FieldEntry));
  h2mod_map_checksum_state_descriptor_ = file->message_type(6);
  static const int h2mod_map_checksum_state_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_map_checksum_state, is_offical_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_map_checksum_state, map_checksum_list_),
  };
  h2mod_map_checksum_state_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      h2mod_map_checksum_state_descriptor_,
      h2mod_map_checksum_state::default_instance_,
      h2mod_map_checksum_state_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_map_checksum_state, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(h2mod_map_checksum_state, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(h2mod_map_checksum_state));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_h2mod_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    H2ModPacket_descriptor_, &H2ModPacket::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    h2mod_set_grenade_descriptor_, &h2mod_set_grenade::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    h2mod_set_team_descriptor_, &h2mod_set_team::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    h2mod_map_info_descriptor_, &h2mod_map_info::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    h2mod_lobby_settings_descriptor_, &h2mod_lobby_settings::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    StringMap_FieldEntry_descriptor_, &StringMap_FieldEntry::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    h2mod_map_checksum_state_descriptor_, &h2mod_map_checksum_state::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_h2mod_2eproto() {
  delete H2ModPacket::default_instance_;
  delete H2ModPacket_reflection_;
  delete h2mod_set_grenade::default_instance_;
  delete h2mod_set_grenade_reflection_;
  delete h2mod_set_team::default_instance_;
  delete h2mod_set_team_reflection_;
  delete h2mod_map_info::default_instance_;
  delete h2mod_map_info_reflection_;
  delete h2mod_lobby_settings::default_instance_;
  delete h2mod_lobby_settings_reflection_;
  delete StringMap_FieldEntry::default_instance_;
  delete StringMap_FieldEntry_reflection_;
  delete h2mod_map_checksum_state::default_instance_;
  delete h2mod_map_checksum_state_reflection_;
}

void protobuf_AddDesc_h2mod_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013h2mod.proto\"\202\003\n\013H2ModPacket\022\037\n\004type\030\001 "
    "\002(\0162\021.H2ModPacket.Type\022+\n\022h2_set_player_"
    "team\030\002 \001(\0132\017.h2mod_set_team\022\'\n\013set_grena"
    "de\030\003 \001(\0132\022.h2mod_set_grenade\022!\n\010map_info"
    "\030\004 \001(\0132\017.h2mod_map_info\022-\n\016lobby_setting"
    "s\030\005 \001(\0132\025.h2mod_lobby_settings\022+\n\010checks"
    "um\030\006 \001(\0132\031.h2mod_map_checksum_state\"}\n\004T"
    "ype\022\023\n\017set_player_team\020\002\022\025\n\021set_unit_gre"
    "nades\020\003\022\024\n\020map_info_request\020\004\022\026\n\022set_lob"
    "by_settings\020\005\022\033\n\027map_checksum_state_sync"
    "\020\006\"@\n\021h2mod_set_grenade\022\014\n\004type\030\001 \002(\r\022\r\n"
    "\005count\030\002 \002(\r\022\016\n\006pIndex\030\003 \002(\r\"1\n\016h2mod_se"
    "t_team\022\021\n\tpeerIndex\030\001 \002(\r\022\014\n\004team\030\002 \002(\r\""
    "6\n\016h2mod_map_info\022\023\n\013mapFileName\030\001 \002(\t\022\017"
    "\n\007mapSize\030\002 \002(\r\"\276\001\n\024h2mod_lobby_settings"
    "\022\034\n\024mp_explosion_physics\030\001 \002(\r\022\022\n\nmp_spu"
    "tnik\030\002 \002(\r\022\033\n\023mp_grunt_bday_party\030\003 \002(\r\022"
    "\033\n\023grenade_chain_react\030\004 \002(\r\022\024\n\014banshee_"
    "bomb\030\005 \002(\r\022\020\n\010mp_blind\030\006 \002(\r\022\022\n\nflashlig"
    "ht\030\007 \002(\r\"2\n\024StringMap_FieldEntry\022\013\n\003key\030"
    "\001 \001(\t\022\r\n\005value\030\002 \001(\t\"`\n\030h2mod_map_checks"
    "um_state\022\022\n\nis_offical\030\001 \002(\010\0220\n\021map_chec"
    "ksum_list\030\002 \003(\0132\025.StringMap_FieldEntry", 918);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "h2mod.proto", &protobuf_RegisterTypes);
  H2ModPacket::default_instance_ = new H2ModPacket();
  h2mod_set_grenade::default_instance_ = new h2mod_set_grenade();
  h2mod_set_team::default_instance_ = new h2mod_set_team();
  h2mod_map_info::default_instance_ = new h2mod_map_info();
  h2mod_lobby_settings::default_instance_ = new h2mod_lobby_settings();
  StringMap_FieldEntry::default_instance_ = new StringMap_FieldEntry();
  h2mod_map_checksum_state::default_instance_ = new h2mod_map_checksum_state();
  H2ModPacket::default_instance_->InitAsDefaultInstance();
  h2mod_set_grenade::default_instance_->InitAsDefaultInstance();
  h2mod_set_team::default_instance_->InitAsDefaultInstance();
  h2mod_map_info::default_instance_->InitAsDefaultInstance();
  h2mod_lobby_settings::default_instance_->InitAsDefaultInstance();
  StringMap_FieldEntry::default_instance_->InitAsDefaultInstance();
  h2mod_map_checksum_state::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_h2mod_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_h2mod_2eproto {
  StaticDescriptorInitializer_h2mod_2eproto() {
    protobuf_AddDesc_h2mod_2eproto();
  }
} static_descriptor_initializer_h2mod_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* H2ModPacket_Type_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return H2ModPacket_Type_descriptor_;
}
bool H2ModPacket_Type_IsValid(int value) {
  switch(value) {
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const H2ModPacket_Type H2ModPacket::set_player_team;
const H2ModPacket_Type H2ModPacket::set_unit_grenades;
const H2ModPacket_Type H2ModPacket::map_info_request;
const H2ModPacket_Type H2ModPacket::set_lobby_settings;
const H2ModPacket_Type H2ModPacket::map_checksum_state_sync;
const H2ModPacket_Type H2ModPacket::Type_MIN;
const H2ModPacket_Type H2ModPacket::Type_MAX;
const int H2ModPacket::Type_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int H2ModPacket::kTypeFieldNumber;
const int H2ModPacket::kH2SetPlayerTeamFieldNumber;
const int H2ModPacket::kSetGrenadeFieldNumber;
const int H2ModPacket::kMapInfoFieldNumber;
const int H2ModPacket::kLobbySettingsFieldNumber;
const int H2ModPacket::kChecksumFieldNumber;
#endif  // !_MSC_VER

H2ModPacket::H2ModPacket()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:H2ModPacket)
}

void H2ModPacket::InitAsDefaultInstance() {
  h2_set_player_team_ = const_cast< ::h2mod_set_team*>(&::h2mod_set_team::default_instance());
  set_grenade_ = const_cast< ::h2mod_set_grenade*>(&::h2mod_set_grenade::default_instance());
  map_info_ = const_cast< ::h2mod_map_info*>(&::h2mod_map_info::default_instance());
  lobby_settings_ = const_cast< ::h2mod_lobby_settings*>(&::h2mod_lobby_settings::default_instance());
  checksum_ = const_cast< ::h2mod_map_checksum_state*>(&::h2mod_map_checksum_state::default_instance());
}

H2ModPacket::H2ModPacket(const H2ModPacket& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:H2ModPacket)
}

void H2ModPacket::SharedCtor() {
  _cached_size_ = 0;
  type_ = 2;
  h2_set_player_team_ = NULL;
  set_grenade_ = NULL;
  map_info_ = NULL;
  lobby_settings_ = NULL;
  checksum_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

H2ModPacket::~H2ModPacket() {
  // @@protoc_insertion_point(destructor:H2ModPacket)
  SharedDtor();
}

void H2ModPacket::SharedDtor() {
  if (this != default_instance_) {
    delete h2_set_player_team_;
    delete set_grenade_;
    delete map_info_;
    delete lobby_settings_;
    delete checksum_;
  }
}

void H2ModPacket::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* H2ModPacket::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return H2ModPacket_descriptor_;
}

const H2ModPacket& H2ModPacket::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_h2mod_2eproto();
  return *default_instance_;
}

H2ModPacket* H2ModPacket::default_instance_ = NULL;

H2ModPacket* H2ModPacket::New() const {
  return new H2ModPacket;
}

void H2ModPacket::Clear() {
  if (_has_bits_[0 / 32] & 63) {
    type_ = 2;
    if (has_h2_set_player_team()) {
      if (h2_set_player_team_ != NULL) h2_set_player_team_->::h2mod_set_team::Clear();
    }
    if (has_set_grenade()) {
      if (set_grenade_ != NULL) set_grenade_->::h2mod_set_grenade::Clear();
    }
    if (has_map_info()) {
      if (map_info_ != NULL) map_info_->::h2mod_map_info::Clear();
    }
    if (has_lobby_settings()) {
      if (lobby_settings_ != NULL) lobby_settings_->::h2mod_lobby_settings::Clear();
    }
    if (has_checksum()) {
      if (checksum_ != NULL) checksum_->::h2mod_map_checksum_state::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool H2ModPacket::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:H2ModPacket)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .H2ModPacket.Type type = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::H2ModPacket_Type_IsValid(value)) {
            set_type(static_cast< ::H2ModPacket_Type >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_h2_set_player_team;
        break;
      }

      // optional .h2mod_set_team h2_set_player_team = 2;
      case 2: {
        if (tag == 18) {
         parse_h2_set_player_team:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_h2_set_player_team()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_set_grenade;
        break;
      }

      // optional .h2mod_set_grenade set_grenade = 3;
      case 3: {
        if (tag == 26) {
         parse_set_grenade:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_set_grenade()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_map_info;
        break;
      }

      // optional .h2mod_map_info map_info = 4;
      case 4: {
        if (tag == 34) {
         parse_map_info:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_map_info()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_lobby_settings;
        break;
      }

      // optional .h2mod_lobby_settings lobby_settings = 5;
      case 5: {
        if (tag == 42) {
         parse_lobby_settings:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_lobby_settings()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_checksum;
        break;
      }

      // optional .h2mod_map_checksum_state checksum = 6;
      case 6: {
        if (tag == 50) {
         parse_checksum:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_checksum()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:H2ModPacket)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:H2ModPacket)
  return false;
#undef DO_
}

void H2ModPacket::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:H2ModPacket)
  // required .H2ModPacket.Type type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // optional .h2mod_set_team h2_set_player_team = 2;
  if (has_h2_set_player_team()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->h2_set_player_team(), output);
  }

  // optional .h2mod_set_grenade set_grenade = 3;
  if (has_set_grenade()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->set_grenade(), output);
  }

  // optional .h2mod_map_info map_info = 4;
  if (has_map_info()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->map_info(), output);
  }

  // optional .h2mod_lobby_settings lobby_settings = 5;
  if (has_lobby_settings()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->lobby_settings(), output);
  }

  // optional .h2mod_map_checksum_state checksum = 6;
  if (has_checksum()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->checksum(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:H2ModPacket)
}

::google::protobuf::uint8* H2ModPacket::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:H2ModPacket)
  // required .H2ModPacket.Type type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // optional .h2mod_set_team h2_set_player_team = 2;
  if (has_h2_set_player_team()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->h2_set_player_team(), target);
  }

  // optional .h2mod_set_grenade set_grenade = 3;
  if (has_set_grenade()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->set_grenade(), target);
  }

  // optional .h2mod_map_info map_info = 4;
  if (has_map_info()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->map_info(), target);
  }

  // optional .h2mod_lobby_settings lobby_settings = 5;
  if (has_lobby_settings()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->lobby_settings(), target);
  }

  // optional .h2mod_map_checksum_state checksum = 6;
  if (has_checksum()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, this->checksum(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:H2ModPacket)
  return target;
}

int H2ModPacket::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .H2ModPacket.Type type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

    // optional .h2mod_set_team h2_set_player_team = 2;
    if (has_h2_set_player_team()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->h2_set_player_team());
    }

    // optional .h2mod_set_grenade set_grenade = 3;
    if (has_set_grenade()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->set_grenade());
    }

    // optional .h2mod_map_info map_info = 4;
    if (has_map_info()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->map_info());
    }

    // optional .h2mod_lobby_settings lobby_settings = 5;
    if (has_lobby_settings()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->lobby_settings());
    }

    // optional .h2mod_map_checksum_state checksum = 6;
    if (has_checksum()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->checksum());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void H2ModPacket::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const H2ModPacket* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const H2ModPacket*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void H2ModPacket::MergeFrom(const H2ModPacket& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_h2_set_player_team()) {
      mutable_h2_set_player_team()->::h2mod_set_team::MergeFrom(from.h2_set_player_team());
    }
    if (from.has_set_grenade()) {
      mutable_set_grenade()->::h2mod_set_grenade::MergeFrom(from.set_grenade());
    }
    if (from.has_map_info()) {
      mutable_map_info()->::h2mod_map_info::MergeFrom(from.map_info());
    }
    if (from.has_lobby_settings()) {
      mutable_lobby_settings()->::h2mod_lobby_settings::MergeFrom(from.lobby_settings());
    }
    if (from.has_checksum()) {
      mutable_checksum()->::h2mod_map_checksum_state::MergeFrom(from.checksum());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void H2ModPacket::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void H2ModPacket::CopyFrom(const H2ModPacket& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool H2ModPacket::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_h2_set_player_team()) {
    if (!this->h2_set_player_team().IsInitialized()) return false;
  }
  if (has_set_grenade()) {
    if (!this->set_grenade().IsInitialized()) return false;
  }
  if (has_map_info()) {
    if (!this->map_info().IsInitialized()) return false;
  }
  if (has_lobby_settings()) {
    if (!this->lobby_settings().IsInitialized()) return false;
  }
  if (has_checksum()) {
    if (!this->checksum().IsInitialized()) return false;
  }
  return true;
}

void H2ModPacket::Swap(H2ModPacket* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(h2_set_player_team_, other->h2_set_player_team_);
    std::swap(set_grenade_, other->set_grenade_);
    std::swap(map_info_, other->map_info_);
    std::swap(lobby_settings_, other->lobby_settings_);
    std::swap(checksum_, other->checksum_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata H2ModPacket::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = H2ModPacket_descriptor_;
  metadata.reflection = H2ModPacket_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int h2mod_set_grenade::kTypeFieldNumber;
const int h2mod_set_grenade::kCountFieldNumber;
const int h2mod_set_grenade::kPIndexFieldNumber;
#endif  // !_MSC_VER

h2mod_set_grenade::h2mod_set_grenade()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:h2mod_set_grenade)
}

void h2mod_set_grenade::InitAsDefaultInstance() {
}

h2mod_set_grenade::h2mod_set_grenade(const h2mod_set_grenade& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:h2mod_set_grenade)
}

void h2mod_set_grenade::SharedCtor() {
  _cached_size_ = 0;
  type_ = 0u;
  count_ = 0u;
  pindex_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

h2mod_set_grenade::~h2mod_set_grenade() {
  // @@protoc_insertion_point(destructor:h2mod_set_grenade)
  SharedDtor();
}

void h2mod_set_grenade::SharedDtor() {
  if (this != default_instance_) {
  }
}

void h2mod_set_grenade::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* h2mod_set_grenade::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return h2mod_set_grenade_descriptor_;
}

const h2mod_set_grenade& h2mod_set_grenade::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_h2mod_2eproto();
  return *default_instance_;
}

h2mod_set_grenade* h2mod_set_grenade::default_instance_ = NULL;

h2mod_set_grenade* h2mod_set_grenade::New() const {
  return new h2mod_set_grenade;
}

void h2mod_set_grenade::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<h2mod_set_grenade*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(type_, pindex_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool h2mod_set_grenade::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:h2mod_set_grenade)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 type = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &type_)));
          set_has_type();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_count;
        break;
      }

      // required uint32 count = 2;
      case 2: {
        if (tag == 16) {
         parse_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &count_)));
          set_has_count();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_pIndex;
        break;
      }

      // required uint32 pIndex = 3;
      case 3: {
        if (tag == 24) {
         parse_pIndex:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &pindex_)));
          set_has_pindex();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:h2mod_set_grenade)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:h2mod_set_grenade)
  return false;
#undef DO_
}

void h2mod_set_grenade::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:h2mod_set_grenade)
  // required uint32 type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->type(), output);
  }

  // required uint32 count = 2;
  if (has_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->count(), output);
  }

  // required uint32 pIndex = 3;
  if (has_pindex()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->pindex(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:h2mod_set_grenade)
}

::google::protobuf::uint8* h2mod_set_grenade::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:h2mod_set_grenade)
  // required uint32 type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->type(), target);
  }

  // required uint32 count = 2;
  if (has_count()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->count(), target);
  }

  // required uint32 pIndex = 3;
  if (has_pindex()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->pindex(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:h2mod_set_grenade)
  return target;
}

int h2mod_set_grenade::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->type());
    }

    // required uint32 count = 2;
    if (has_count()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->count());
    }

    // required uint32 pIndex = 3;
    if (has_pindex()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->pindex());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void h2mod_set_grenade::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const h2mod_set_grenade* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const h2mod_set_grenade*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void h2mod_set_grenade::MergeFrom(const h2mod_set_grenade& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_count()) {
      set_count(from.count());
    }
    if (from.has_pindex()) {
      set_pindex(from.pindex());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void h2mod_set_grenade::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void h2mod_set_grenade::CopyFrom(const h2mod_set_grenade& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool h2mod_set_grenade::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void h2mod_set_grenade::Swap(h2mod_set_grenade* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(count_, other->count_);
    std::swap(pindex_, other->pindex_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata h2mod_set_grenade::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = h2mod_set_grenade_descriptor_;
  metadata.reflection = h2mod_set_grenade_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int h2mod_set_team::kPeerIndexFieldNumber;
const int h2mod_set_team::kTeamFieldNumber;
#endif  // !_MSC_VER

h2mod_set_team::h2mod_set_team()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:h2mod_set_team)
}

void h2mod_set_team::InitAsDefaultInstance() {
}

h2mod_set_team::h2mod_set_team(const h2mod_set_team& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:h2mod_set_team)
}

void h2mod_set_team::SharedCtor() {
  _cached_size_ = 0;
  peerindex_ = 0u;
  team_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

h2mod_set_team::~h2mod_set_team() {
  // @@protoc_insertion_point(destructor:h2mod_set_team)
  SharedDtor();
}

void h2mod_set_team::SharedDtor() {
  if (this != default_instance_) {
  }
}

void h2mod_set_team::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* h2mod_set_team::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return h2mod_set_team_descriptor_;
}

const h2mod_set_team& h2mod_set_team::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_h2mod_2eproto();
  return *default_instance_;
}

h2mod_set_team* h2mod_set_team::default_instance_ = NULL;

h2mod_set_team* h2mod_set_team::New() const {
  return new h2mod_set_team;
}

void h2mod_set_team::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<h2mod_set_team*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(peerindex_, team_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool h2mod_set_team::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:h2mod_set_team)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 peerIndex = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &peerindex_)));
          set_has_peerindex();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_team;
        break;
      }

      // required uint32 team = 2;
      case 2: {
        if (tag == 16) {
         parse_team:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &team_)));
          set_has_team();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:h2mod_set_team)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:h2mod_set_team)
  return false;
#undef DO_
}

void h2mod_set_team::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:h2mod_set_team)
  // required uint32 peerIndex = 1;
  if (has_peerindex()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->peerindex(), output);
  }

  // required uint32 team = 2;
  if (has_team()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->team(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:h2mod_set_team)
}

::google::protobuf::uint8* h2mod_set_team::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:h2mod_set_team)
  // required uint32 peerIndex = 1;
  if (has_peerindex()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->peerindex(), target);
  }

  // required uint32 team = 2;
  if (has_team()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->team(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:h2mod_set_team)
  return target;
}

int h2mod_set_team::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 peerIndex = 1;
    if (has_peerindex()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->peerindex());
    }

    // required uint32 team = 2;
    if (has_team()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->team());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void h2mod_set_team::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const h2mod_set_team* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const h2mod_set_team*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void h2mod_set_team::MergeFrom(const h2mod_set_team& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_peerindex()) {
      set_peerindex(from.peerindex());
    }
    if (from.has_team()) {
      set_team(from.team());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void h2mod_set_team::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void h2mod_set_team::CopyFrom(const h2mod_set_team& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool h2mod_set_team::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void h2mod_set_team::Swap(h2mod_set_team* other) {
  if (other != this) {
    std::swap(peerindex_, other->peerindex_);
    std::swap(team_, other->team_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata h2mod_set_team::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = h2mod_set_team_descriptor_;
  metadata.reflection = h2mod_set_team_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int h2mod_map_info::kMapFileNameFieldNumber;
const int h2mod_map_info::kMapSizeFieldNumber;
#endif  // !_MSC_VER

h2mod_map_info::h2mod_map_info()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:h2mod_map_info)
}

void h2mod_map_info::InitAsDefaultInstance() {
}

h2mod_map_info::h2mod_map_info(const h2mod_map_info& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:h2mod_map_info)
}

void h2mod_map_info::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  mapfilename_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mapsize_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

h2mod_map_info::~h2mod_map_info() {
  // @@protoc_insertion_point(destructor:h2mod_map_info)
  SharedDtor();
}

void h2mod_map_info::SharedDtor() {
  if (mapfilename_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete mapfilename_;
  }
  if (this != default_instance_) {
  }
}

void h2mod_map_info::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* h2mod_map_info::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return h2mod_map_info_descriptor_;
}

const h2mod_map_info& h2mod_map_info::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_h2mod_2eproto();
  return *default_instance_;
}

h2mod_map_info* h2mod_map_info::default_instance_ = NULL;

h2mod_map_info* h2mod_map_info::New() const {
  return new h2mod_map_info;
}

void h2mod_map_info::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_mapfilename()) {
      if (mapfilename_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        mapfilename_->clear();
      }
    }
    mapsize_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool h2mod_map_info::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:h2mod_map_info)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string mapFileName = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_mapfilename()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->mapfilename().data(), this->mapfilename().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "mapfilename");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_mapSize;
        break;
      }

      // required uint32 mapSize = 2;
      case 2: {
        if (tag == 16) {
         parse_mapSize:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &mapsize_)));
          set_has_mapsize();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:h2mod_map_info)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:h2mod_map_info)
  return false;
#undef DO_
}

void h2mod_map_info::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:h2mod_map_info)
  // required string mapFileName = 1;
  if (has_mapfilename()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->mapfilename().data(), this->mapfilename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "mapfilename");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->mapfilename(), output);
  }

  // required uint32 mapSize = 2;
  if (has_mapsize()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->mapsize(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:h2mod_map_info)
}

::google::protobuf::uint8* h2mod_map_info::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:h2mod_map_info)
  // required string mapFileName = 1;
  if (has_mapfilename()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->mapfilename().data(), this->mapfilename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "mapfilename");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->mapfilename(), target);
  }

  // required uint32 mapSize = 2;
  if (has_mapsize()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->mapsize(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:h2mod_map_info)
  return target;
}

int h2mod_map_info::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string mapFileName = 1;
    if (has_mapfilename()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->mapfilename());
    }

    // required uint32 mapSize = 2;
    if (has_mapsize()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->mapsize());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void h2mod_map_info::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const h2mod_map_info* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const h2mod_map_info*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void h2mod_map_info::MergeFrom(const h2mod_map_info& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_mapfilename()) {
      set_mapfilename(from.mapfilename());
    }
    if (from.has_mapsize()) {
      set_mapsize(from.mapsize());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void h2mod_map_info::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void h2mod_map_info::CopyFrom(const h2mod_map_info& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool h2mod_map_info::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void h2mod_map_info::Swap(h2mod_map_info* other) {
  if (other != this) {
    std::swap(mapfilename_, other->mapfilename_);
    std::swap(mapsize_, other->mapsize_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata h2mod_map_info::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = h2mod_map_info_descriptor_;
  metadata.reflection = h2mod_map_info_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int h2mod_lobby_settings::kMpExplosionPhysicsFieldNumber;
const int h2mod_lobby_settings::kMpSputnikFieldNumber;
const int h2mod_lobby_settings::kMpGruntBdayPartyFieldNumber;
const int h2mod_lobby_settings::kGrenadeChainReactFieldNumber;
const int h2mod_lobby_settings::kBansheeBombFieldNumber;
const int h2mod_lobby_settings::kMpBlindFieldNumber;
const int h2mod_lobby_settings::kFlashlightFieldNumber;
#endif  // !_MSC_VER

h2mod_lobby_settings::h2mod_lobby_settings()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:h2mod_lobby_settings)
}

void h2mod_lobby_settings::InitAsDefaultInstance() {
}

h2mod_lobby_settings::h2mod_lobby_settings(const h2mod_lobby_settings& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:h2mod_lobby_settings)
}

void h2mod_lobby_settings::SharedCtor() {
  _cached_size_ = 0;
  mp_explosion_physics_ = 0u;
  mp_sputnik_ = 0u;
  mp_grunt_bday_party_ = 0u;
  grenade_chain_react_ = 0u;
  banshee_bomb_ = 0u;
  mp_blind_ = 0u;
  flashlight_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

h2mod_lobby_settings::~h2mod_lobby_settings() {
  // @@protoc_insertion_point(destructor:h2mod_lobby_settings)
  SharedDtor();
}

void h2mod_lobby_settings::SharedDtor() {
  if (this != default_instance_) {
  }
}

void h2mod_lobby_settings::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* h2mod_lobby_settings::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return h2mod_lobby_settings_descriptor_;
}

const h2mod_lobby_settings& h2mod_lobby_settings::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_h2mod_2eproto();
  return *default_instance_;
}

h2mod_lobby_settings* h2mod_lobby_settings::default_instance_ = NULL;

h2mod_lobby_settings* h2mod_lobby_settings::New() const {
  return new h2mod_lobby_settings;
}

void h2mod_lobby_settings::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<h2mod_lobby_settings*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 127) {
    ZR_(mp_explosion_physics_, flashlight_);
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool h2mod_lobby_settings::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:h2mod_lobby_settings)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 mp_explosion_physics = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &mp_explosion_physics_)));
          set_has_mp_explosion_physics();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_mp_sputnik;
        break;
      }

      // required uint32 mp_sputnik = 2;
      case 2: {
        if (tag == 16) {
         parse_mp_sputnik:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &mp_sputnik_)));
          set_has_mp_sputnik();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_mp_grunt_bday_party;
        break;
      }

      // required uint32 mp_grunt_bday_party = 3;
      case 3: {
        if (tag == 24) {
         parse_mp_grunt_bday_party:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &mp_grunt_bday_party_)));
          set_has_mp_grunt_bday_party();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_grenade_chain_react;
        break;
      }

      // required uint32 grenade_chain_react = 4;
      case 4: {
        if (tag == 32) {
         parse_grenade_chain_react:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &grenade_chain_react_)));
          set_has_grenade_chain_react();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_banshee_bomb;
        break;
      }

      // required uint32 banshee_bomb = 5;
      case 5: {
        if (tag == 40) {
         parse_banshee_bomb:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &banshee_bomb_)));
          set_has_banshee_bomb();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_mp_blind;
        break;
      }

      // required uint32 mp_blind = 6;
      case 6: {
        if (tag == 48) {
         parse_mp_blind:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &mp_blind_)));
          set_has_mp_blind();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_flashlight;
        break;
      }

      // required uint32 flashlight = 7;
      case 7: {
        if (tag == 56) {
         parse_flashlight:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &flashlight_)));
          set_has_flashlight();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:h2mod_lobby_settings)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:h2mod_lobby_settings)
  return false;
#undef DO_
}

void h2mod_lobby_settings::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:h2mod_lobby_settings)
  // required uint32 mp_explosion_physics = 1;
  if (has_mp_explosion_physics()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->mp_explosion_physics(), output);
  }

  // required uint32 mp_sputnik = 2;
  if (has_mp_sputnik()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->mp_sputnik(), output);
  }

  // required uint32 mp_grunt_bday_party = 3;
  if (has_mp_grunt_bday_party()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->mp_grunt_bday_party(), output);
  }

  // required uint32 grenade_chain_react = 4;
  if (has_grenade_chain_react()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->grenade_chain_react(), output);
  }

  // required uint32 banshee_bomb = 5;
  if (has_banshee_bomb()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->banshee_bomb(), output);
  }

  // required uint32 mp_blind = 6;
  if (has_mp_blind()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->mp_blind(), output);
  }

  // required uint32 flashlight = 7;
  if (has_flashlight()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->flashlight(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:h2mod_lobby_settings)
}

::google::protobuf::uint8* h2mod_lobby_settings::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:h2mod_lobby_settings)
  // required uint32 mp_explosion_physics = 1;
  if (has_mp_explosion_physics()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->mp_explosion_physics(), target);
  }

  // required uint32 mp_sputnik = 2;
  if (has_mp_sputnik()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->mp_sputnik(), target);
  }

  // required uint32 mp_grunt_bday_party = 3;
  if (has_mp_grunt_bday_party()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->mp_grunt_bday_party(), target);
  }

  // required uint32 grenade_chain_react = 4;
  if (has_grenade_chain_react()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->grenade_chain_react(), target);
  }

  // required uint32 banshee_bomb = 5;
  if (has_banshee_bomb()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->banshee_bomb(), target);
  }

  // required uint32 mp_blind = 6;
  if (has_mp_blind()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->mp_blind(), target);
  }

  // required uint32 flashlight = 7;
  if (has_flashlight()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->flashlight(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:h2mod_lobby_settings)
  return target;
}

int h2mod_lobby_settings::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 mp_explosion_physics = 1;
    if (has_mp_explosion_physics()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->mp_explosion_physics());
    }

    // required uint32 mp_sputnik = 2;
    if (has_mp_sputnik()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->mp_sputnik());
    }

    // required uint32 mp_grunt_bday_party = 3;
    if (has_mp_grunt_bday_party()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->mp_grunt_bday_party());
    }

    // required uint32 grenade_chain_react = 4;
    if (has_grenade_chain_react()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->grenade_chain_react());
    }

    // required uint32 banshee_bomb = 5;
    if (has_banshee_bomb()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->banshee_bomb());
    }

    // required uint32 mp_blind = 6;
    if (has_mp_blind()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->mp_blind());
    }

    // required uint32 flashlight = 7;
    if (has_flashlight()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->flashlight());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void h2mod_lobby_settings::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const h2mod_lobby_settings* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const h2mod_lobby_settings*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void h2mod_lobby_settings::MergeFrom(const h2mod_lobby_settings& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_mp_explosion_physics()) {
      set_mp_explosion_physics(from.mp_explosion_physics());
    }
    if (from.has_mp_sputnik()) {
      set_mp_sputnik(from.mp_sputnik());
    }
    if (from.has_mp_grunt_bday_party()) {
      set_mp_grunt_bday_party(from.mp_grunt_bday_party());
    }
    if (from.has_grenade_chain_react()) {
      set_grenade_chain_react(from.grenade_chain_react());
    }
    if (from.has_banshee_bomb()) {
      set_banshee_bomb(from.banshee_bomb());
    }
    if (from.has_mp_blind()) {
      set_mp_blind(from.mp_blind());
    }
    if (from.has_flashlight()) {
      set_flashlight(from.flashlight());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void h2mod_lobby_settings::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void h2mod_lobby_settings::CopyFrom(const h2mod_lobby_settings& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool h2mod_lobby_settings::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000007f) != 0x0000007f) return false;

  return true;
}

void h2mod_lobby_settings::Swap(h2mod_lobby_settings* other) {
  if (other != this) {
    std::swap(mp_explosion_physics_, other->mp_explosion_physics_);
    std::swap(mp_sputnik_, other->mp_sputnik_);
    std::swap(mp_grunt_bday_party_, other->mp_grunt_bday_party_);
    std::swap(grenade_chain_react_, other->grenade_chain_react_);
    std::swap(banshee_bomb_, other->banshee_bomb_);
    std::swap(mp_blind_, other->mp_blind_);
    std::swap(flashlight_, other->flashlight_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata h2mod_lobby_settings::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = h2mod_lobby_settings_descriptor_;
  metadata.reflection = h2mod_lobby_settings_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int StringMap_FieldEntry::kKeyFieldNumber;
const int StringMap_FieldEntry::kValueFieldNumber;
#endif  // !_MSC_VER

StringMap_FieldEntry::StringMap_FieldEntry()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:StringMap_FieldEntry)
}

void StringMap_FieldEntry::InitAsDefaultInstance() {
}

StringMap_FieldEntry::StringMap_FieldEntry(const StringMap_FieldEntry& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:StringMap_FieldEntry)
}

void StringMap_FieldEntry::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  key_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

StringMap_FieldEntry::~StringMap_FieldEntry() {
  // @@protoc_insertion_point(destructor:StringMap_FieldEntry)
  SharedDtor();
}

void StringMap_FieldEntry::SharedDtor() {
  if (key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete key_;
  }
  if (value_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete value_;
  }
  if (this != default_instance_) {
  }
}

void StringMap_FieldEntry::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StringMap_FieldEntry::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return StringMap_FieldEntry_descriptor_;
}

const StringMap_FieldEntry& StringMap_FieldEntry::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_h2mod_2eproto();
  return *default_instance_;
}

StringMap_FieldEntry* StringMap_FieldEntry::default_instance_ = NULL;

StringMap_FieldEntry* StringMap_FieldEntry::New() const {
  return new StringMap_FieldEntry;
}

void StringMap_FieldEntry::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_key()) {
      if (key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        key_->clear();
      }
    }
    if (has_value()) {
      if (value_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        value_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool StringMap_FieldEntry::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:StringMap_FieldEntry)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string key = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->key().data(), this->key().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "key");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_value;
        break;
      }

      // optional string value = 2;
      case 2: {
        if (tag == 18) {
         parse_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->value().data(), this->value().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "value");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:StringMap_FieldEntry)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:StringMap_FieldEntry)
  return false;
#undef DO_
}

void StringMap_FieldEntry::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:StringMap_FieldEntry)
  // optional string key = 1;
  if (has_key()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->key(), output);
  }

  // optional string value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->value(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:StringMap_FieldEntry)
}

::google::protobuf::uint8* StringMap_FieldEntry::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:StringMap_FieldEntry)
  // optional string key = 1;
  if (has_key()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }

  // optional string value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->value(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:StringMap_FieldEntry)
  return target;
}

int StringMap_FieldEntry::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string key = 1;
    if (has_key()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->key());
    }

    // optional string value = 2;
    if (has_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->value());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StringMap_FieldEntry::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const StringMap_FieldEntry* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const StringMap_FieldEntry*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void StringMap_FieldEntry::MergeFrom(const StringMap_FieldEntry& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_key()) {
      set_key(from.key());
    }
    if (from.has_value()) {
      set_value(from.value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void StringMap_FieldEntry::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StringMap_FieldEntry::CopyFrom(const StringMap_FieldEntry& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StringMap_FieldEntry::IsInitialized() const {

  return true;
}

void StringMap_FieldEntry::Swap(StringMap_FieldEntry* other) {
  if (other != this) {
    std::swap(key_, other->key_);
    std::swap(value_, other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata StringMap_FieldEntry::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = StringMap_FieldEntry_descriptor_;
  metadata.reflection = StringMap_FieldEntry_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int h2mod_map_checksum_state::kIsOfficalFieldNumber;
const int h2mod_map_checksum_state::kMapChecksumListFieldNumber;
#endif  // !_MSC_VER

h2mod_map_checksum_state::h2mod_map_checksum_state()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:h2mod_map_checksum_state)
}

void h2mod_map_checksum_state::InitAsDefaultInstance() {
}

h2mod_map_checksum_state::h2mod_map_checksum_state(const h2mod_map_checksum_state& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:h2mod_map_checksum_state)
}

void h2mod_map_checksum_state::SharedCtor() {
  _cached_size_ = 0;
  is_offical_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

h2mod_map_checksum_state::~h2mod_map_checksum_state() {
  // @@protoc_insertion_point(destructor:h2mod_map_checksum_state)
  SharedDtor();
}

void h2mod_map_checksum_state::SharedDtor() {
  if (this != default_instance_) {
  }
}

void h2mod_map_checksum_state::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* h2mod_map_checksum_state::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return h2mod_map_checksum_state_descriptor_;
}

const h2mod_map_checksum_state& h2mod_map_checksum_state::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_h2mod_2eproto();
  return *default_instance_;
}

h2mod_map_checksum_state* h2mod_map_checksum_state::default_instance_ = NULL;

h2mod_map_checksum_state* h2mod_map_checksum_state::New() const {
  return new h2mod_map_checksum_state;
}

void h2mod_map_checksum_state::Clear() {
  is_offical_ = false;
  map_checksum_list_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool h2mod_map_checksum_state::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:h2mod_map_checksum_state)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bool is_offical = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_offical_)));
          set_has_is_offical();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_map_checksum_list;
        break;
      }

      // repeated .StringMap_FieldEntry map_checksum_list = 2;
      case 2: {
        if (tag == 18) {
         parse_map_checksum_list:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_map_checksum_list()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_map_checksum_list;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:h2mod_map_checksum_state)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:h2mod_map_checksum_state)
  return false;
#undef DO_
}

void h2mod_map_checksum_state::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:h2mod_map_checksum_state)
  // required bool is_offical = 1;
  if (has_is_offical()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->is_offical(), output);
  }

  // repeated .StringMap_FieldEntry map_checksum_list = 2;
  for (int i = 0; i < this->map_checksum_list_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->map_checksum_list(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:h2mod_map_checksum_state)
}

::google::protobuf::uint8* h2mod_map_checksum_state::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:h2mod_map_checksum_state)
  // required bool is_offical = 1;
  if (has_is_offical()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->is_offical(), target);
  }

  // repeated .StringMap_FieldEntry map_checksum_list = 2;
  for (int i = 0; i < this->map_checksum_list_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->map_checksum_list(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:h2mod_map_checksum_state)
  return target;
}

int h2mod_map_checksum_state::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bool is_offical = 1;
    if (has_is_offical()) {
      total_size += 1 + 1;
    }

  }
  // repeated .StringMap_FieldEntry map_checksum_list = 2;
  total_size += 1 * this->map_checksum_list_size();
  for (int i = 0; i < this->map_checksum_list_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->map_checksum_list(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void h2mod_map_checksum_state::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const h2mod_map_checksum_state* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const h2mod_map_checksum_state*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void h2mod_map_checksum_state::MergeFrom(const h2mod_map_checksum_state& from) {
  GOOGLE_CHECK_NE(&from, this);
  map_checksum_list_.MergeFrom(from.map_checksum_list_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_is_offical()) {
      set_is_offical(from.is_offical());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void h2mod_map_checksum_state::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void h2mod_map_checksum_state::CopyFrom(const h2mod_map_checksum_state& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool h2mod_map_checksum_state::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void h2mod_map_checksum_state::Swap(h2mod_map_checksum_state* other) {
  if (other != this) {
    std::swap(is_offical_, other->is_offical_);
    map_checksum_list_.Swap(&other->map_checksum_list_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata h2mod_map_checksum_state::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = h2mod_map_checksum_state_descriptor_;
  metadata.reflection = h2mod_map_checksum_state_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
