#pragma once

namespace Blam
{
	namespace Enums
	{
		namespace Tags
		{
			enum class TagGroupTypes : __int32
			{
				model = 'hlmt',
				rendermodel = 'mode',
				collisionmodel = 'coll',
				physicsmodel = 'phmo',
				bitmap = 'bitm',
				colortable = 'colo',
				multilingualunicodestringlist = 'unic',
				unit = 'unit',
				biped = 'bipd',
				vehicle = 'vehi',
				scenery = 'scen',
				crate = 'bloc',
				creature = 'crea',
				physics = 'phys',
				object = 'obje',
				contrail = 'cont',
				weapon = 'weap',
				light = 'ligh',
				effect = 'effe',
				particle = 'prt3',
				particlemodel = 'PRTM',
				particlephysics = 'pmov',
				globals = 'matg',
				sound = 'snd!',
				soundlooping = 'lsnd',
				item = 'item',
				equipment = 'eqip',
				antenna = 'ant!',
				lightvolume = 'MGS2',
				liquid = 'tdtl',
				cellularautomata = 'devo',
				cellularautomata2d = 'whip',
				stereosystem = 'BooM',
				cameratrack = 'trak',
				projectile = 'proj',
				device = 'devi',
				devicemachine = 'mach',
				devicecontrol = 'ctrl',
				devicelightfixture = 'lifi',
				pointphysics = 'pphy',
				scenariostructurelightmap = 'ltmp',
				scenariostructurebsp = 'sbsp',
				scenario = 'scnr',
				shader = 'shad',
				shadertemplate = 'stem',
				shaderlightresponse = 'slit',
				shaderpass = 'spas',
				vertexshader = 'vrtx',
				pixelshader = 'pixl',
				decoratorset = 'DECR',
				decorators = 'DECP',
				sky = 'sky ',
				wind = 'wind',
				soundenvironment = 'snde',
				lensflare = 'lens',
				planarfog = 'fog ',
				patchyfog = 'fpch',
				meter = 'metr',
				decal = 'deca',
				colony = 'coln',
				damageeffect = 'jpt!',
				dialogue = 'uldg',
				itemcollection = 'itmc',
				vehiclecollection = 'vehc',
				weaponhudinterface = 'wphi',
				grenadehudinterface = 'grhi',
				unithudinterface = 'unhi',
				newhuddefinition = 'nhdt',
				hudnumber = 'hud#',
				hudglobals = 'hudg',
				multiplayerscenariodescription = 'mply',
				detailobjectcollection = 'dobc',
				soundscenery = 'ssce',
				hudmessagetext = 'hmt ',
				userinterfacescreenwidgetdefinition = 'wgit',
				userinterfacelistskindefinition = 'skin',
				userinterfaceglobalsdefinition = 'wgtz',
				userinterfacesharedglobalsdefinition = 'wigl',
				textvaluepairdefinition = 'sily',
				multiplayervariantsettingsinterfacedefinition = 'goof',
				materialeffects = 'foot',
				garbage = 'garb',
				style = 'stly',
				character = 'char',
				aidialogueglobals = 'adlg',
				aimissiondialogue = 'mdlg',
				scenariosceneryresource = '*cen',
				scenariobipedsresource = '*ipd',
				scenariovehiclesresource = '*ehi',
				scenarioequipmentresource = '*qip',
				scenarioweaponsresource = '*eap',
				scenariosoundsceneryresource = '*sce',
				scenariolightsresource = '*igh',
				scenariodevicesresource = 'dgr*',
				scenariodecalsresource = 'dec*',
				scenariocinematicsresource = 'cin*',
				scenariotriggervolumesresource = 'trg*',
				scenarioclusterdataresource = 'clu*',
				scenariocreatureresource = '*rea',
				scenariodecoratorsresource = 'dc*s',
				scenariostructurelightingresource = 'sslt',
				scenariohssourcefile = 'hsc*',
				scenarioairesource = 'ai**',
				scenariocommentsresource = '/**/',
				breakablesurface = 'bsdt',
				materialphysics = 'mpdt',
				soundclasses = 'sncl',
				multiplayerglobals = 'mulg',
				soundeffecttemplate = '<fx>',
				soundeffectcollection = 'sfx+',
				chocolatemountain = 'gldf',
				modelanimationgraph = 'jmad',
				cloth = 'clwd',
				screeneffect = 'egor',
				weathersystem = 'weat',
				soundmix = 'snmx',
				sounddialogueconstants = 'spk!',
				soundcachefilegestalt = 'ugh!',
				cachefilesound = '$#!+',
				mousecursordefinition = 'mcsr',
			};
		}
	}
}
