//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by h2admin.rc
//

#define IDI_ICON1                       1

#define kablam_string_test              100
#define kablam_string_description_label 101
#define kablam_string_usage_label       102
#define kablam_string_help_more_info_hint 103
#define kablam_string_available_commands_label 104
#define kablam_string_err_unrecognized_command_hint 105
#define kablam_string_err_insufficient_memory 106
#define kablam_string_help_exit_desc    107
#define kablam_string_help_exit_usage   108
#define kablam_string_err_too_many_args 109
#define kablam_string_info_match_ended  110
#define kablam_string_status_server_not_active 111
#define kablam_string_help_skip_desc    112
#define kablam_string_help_skip_usage   113
#define kablam_string_err_missing_player_name 114
#define kablam_string_info_player_booted 115
#define kablam_string_err_player_not_found 116
#define kablam_string_help_kick_desc    117
#define kablam_string_help_kick_usage   118
#define kablam_string_help_sendmsg_usage 119
#define kablam_string_err_match_missing_setting 120
#define kablam_string_err_invalid_setting_for_variant 121
#define kablam_string_err_variant_missing_name 122
#define kablam_string_warn_variants_overflow 123
#define kablam_string_warn_matches_overflow 124
#define kablam_string_warn_unknown      125
#define kablam_string_err_file_not_found 126
#define kablam_string_err_access_denied 127
#define kablam_string_err_playlist_no_valid_matches 128
#define kablam_string_err_playlist_read_failed 129
#define kablam_string_err_variant_missing_type_or_base 130
#define kablam_string_hint_help_for_command 131
#define kablam_string_err_command_too_long 132
#define kablam_string_err_rpc_console_init_failed 133
#define kablam_string_err_text_console_init_failed 134
#define kablam_string_live_signout_in_progress 135
#define kablam_string_live_signin_already_in_progress 136
#define kablam_string_live_must_sign_out_first 137
#define kablam_string_live_not_signed_in 138
#define kablam_string_info_playlist_loaded 139
#define kablam_string_help_play_desc    140
#define kablam_string_help_play_usage   141
#define kablam_string_err_missing_subcommand 142
#define kablam_string_help_name_desc    143
#define kablam_string_help_name_usage   144
#define kablam_string_info_session_description_changed 145
#define kablam_string_info_session_name_changed 147
#define kablam_string_help_status_desc  148
#define kablam_string_help_status_usage 149
#define kablam_string_err_missing_message 150
#define kablam_string_err_too_many_args_quotes_hint 151
#define kablam_string_err_text_too_long 152
#define kablam_string_info_no_players   153
#define kablam_string_info_message_sent 154
#define kablam_string_info_no_players_in_session 155
#define kablam_string_err_send_message_failed 156
#define kablam_string_help_sendmsg_desc 157
#define kablam_string_err_playlist_section_dup 158
#define kablam_string_err_variant_name_duplicate 159
#define kablam_string_err_unknown_setting 160
#define kablam_string_err_unknown_section 161
#define kablam_string_err_invalid_value_for_setting 162
#define kablam_string_err_already_set   163
#define kablam_string_warnings_label    164
#define kablam_string_line_label        165
#define kablam_string_help_description_desc 166
#define kablam_string_help_description_usage 167
#define kablam_string_err_missing_argument 168
#define kablam_string_err_missing_gamertag 169
#define kablam_string_err_invalid_argument 170
#define kablam_string_err_missing_ip_or_cidr 171
#define kablam_string_err_invalid_ip_or_cidr 172
#define kablam_string_err_missing_ethernet 173
#define kablam_string_err_invalid_ethernet 174
#define kablam_string_err_invalid_duration 175
#define kablam_string_info_list_empty   176
#define kablam_string_info_vip_added    177
#define kablam_string_info_vip_removed  178
#define kablam_string_err_vip_list_full 179
#define kablam_string_err_vip_not_found 180
#define kablam_string_info_vip_cleared  181
#define kablam_string_info_ban_added    182
#define kablam_string_info_ban_removed  183
#define kablam_string_err_ban_not_found 184
#define kablam_string_info_ban_cleared  185
#define kablam_string_err_ban_list_full 186
#define kablam_string_err_unknown_command 187
#define kablam_string_err_invalid_gamertag 188
#define kablam_string_help_unban_desc   189
#define kablam_string_help_unban_usage  190
#define kablam_string_help_ban_desc     191
#define kablam_string_help_ban_usage    192
#define kablam_string_help_vip_desc     193
#define kablam_string_help_vip_usage    194
#define kablam_string_help_live_desc    195
#define kablam_string_help_live_usage   196
#define kablam_string_until_label       197
#define kablam_string_err_missing_product_key 198
#define kablam_string_prompt_password   199
#define kablam_string_err_product_key_set_failed 200
#define kablam_string_info_autosignin_enabled 201
#define kablam_string_err_autosignin_failed 202
#define kablam_string_title_h2_dedicated_server 203
#define kablam_string_copyright_2006_ms 204
#define kablam_string_live_signout_already_in_progress 205
#define kablam_string_live_signin_in_progress 206
#define kablam_string_info_autosignin_password_deleted 207
#define kablam_string_err_autosignin_password_not_found 208
#define kablam_string_prompt_confirm_password 209
#define kablam_string_err_passwords_do_not_match 210
#define kablam_string_err_product_key_invalid 211
#define kablam_string_info_product_key_set 212
#define kablam_string_info_signing_in_manual 213
#define kablam_string_info_signed_in_live 214
#define kablam_string_info_signing_out_live 215
#define kablam_string_info_not_signed_in_live 216
#define kablam_string_err_live_signin_failed 217
#define kablam_string_info_live_disconnected 218
#define kablam_string_err_live_service_unreachable 219
#define kablam_string_err_server_product_key_missing 220
#define kablam_string_err_server_product_key_invalid 221
#define kablam_string_err_live_server_banned 222
#define kablam_string_err_live_server_limit_exceeded 223
#define kablam_string_err_live_update_required 224
#define kablam_string_err_live_signed_in_elsewhere 225
#define kablam_string_err_live_unavailable 226
#define kablam_string_err_live_invalid_credentials 227
#define kablam_string_err_live_invalid_id 228
#define kablam_string_hint_live_autosignin 229
#define kablam_string_info_mode_live    230
#define kablam_string_info_mode_lan     231
#define kablam_string_title_h2_dedicated_server_2 232
#define kablam_string_tagline_provides_awesomeness 233
#define kablam_string_err_builtin_maps_load_failed 234
#define kablam_string_err_input_console_init_failed 235
#define kablam_string_err_instance_already_running 236
#define kablam_string_err_port_in_use   237
#define kablam_string_err_missing_service_username 238
#define kablam_string_err_missing_instance_name 239
#define kablam_string_err_invalid_instance_name 240
#define kablam_string_err_install_path_too_long 241
#define kablam_string_err_admin_required 242
#define kablam_string_info_service_already_installed 243
#define kablam_string_info_install_success 244
#define kablam_string_err_install_failed 245
#define kablam_string_err_service_not_installed 246
#define kablam_string_err_uninstall_pending 247
#define kablam_string_info_uninstall_success 248
#define kablam_string_err_uninstall_failed 249
#define kablam_string_err_missing_network_mode_flag 250
#define kablam_string_err_command_live_only 251
#define kablam_string_err_command_lan_only 252
#define kablam_string_err_variant_both_type_and_base 254
#define kablam_string_err_invalid_base_variant 256
#define kablam_string_err_variant_missing_or_invalid 258
#define kablam_string_err_map_missing_or_invalid 259
#define kablam_string_label_playlist    260
#define kablam_string_err_playlist_not_loaded 261
#define kablam_string_hint_playlist_how_to_load 262
#define kablam_string_help_playing_desc 263
#define kablam_string_help_playing_usage 264
#define kablam_string_help_server_cli_usage 265
#define kablam_string_err_missing_network_mode 266
#define kablam_string_err_registry_permissions 267
#define kablam_string_err_service_account_create_failed 268
#define kablam_string_err_service_username_invalid 270
#define kablam_string_err_service_account_login_failed 271
#define kablam_string_err_service_account_profile_failed 272
#define kablam_string_label_service_account 273
#define kablam_string_label_service     274
#define kablam_string_err_uninstall_pending_blocking 275
#define kablam_string_err_file_open_access_denied 276
#define kablam_string_info_statsfolder_changed 277
#define kablam_string_err_statsfolder_invalid 278
#define kablam_string_err_statsfolder_not_writeable 279
#define kablam_string_info_stats_export_disabled 280
#define kablam_string_help_statsfolder_desc 281
#define kablam_string_help_statsfolder_usage 282
#define kablam_string_err_privacy_mode_invalid 283
#define kablam_string_help_privacy_desc 284
#define kablam_string_help_privacy_usage 285
#define kablam_string_privacy_open_label 286
#define kablam_string_privacy_gold_label 287
#define kablam_string_privacy_vip_label 288
#define kablam_string_err_privacy_setting_invalid 289
#define kablam_string_info_privacy_changed 290
#define kablam_string_help_players_desc 291
#define kablam_string_help_players_usage 292
#define kablam_string_err_player_count_invalid 293
#define kablam_string_err_player_count_out_of_range 294
#define kablam_string_info_player_count_changed 295
#define kablam_string_label_elapsed_time_fmt 296
#define kablam_string_label_time_remaining_fmt 297
#define kablam_string_err_service_account_already_assigned 298
#define kablam_string_err_variant_invalid_utf16 299
#define kablam_string_err_variant_pipe_forbidden 300
#define kablam_string_info_playlist_entry_skipped 301
#define kablam_string_info_match_ending_waiting 302
#define kablam_string_label_service_account_group_name 303
#define kablam_string_label_service_admins_group_desc 304
#define kablam_string_label_server_admins_group 305
#define kablam_string_err_server_admins_group_setup 306
#define kablam_string_info_user_added_to_admins 307
#define kablam_string_info_scanning_custom_maps 308
#define kablam_string_info_done         309
#define kablam_string_title_admin_console 10000
#define kablam_string_copyright_2006_2007_ms 10001
#define kablam_string_info_connecting_to_server 10002
#define kablam_string_err_connect_failed 10003
#define kablam_string_info_connected    10004
#define kablam_string_err_access_denied_admin_console 10005
#define kablam_string_err_connect_service_not_started 10006
#define kablam_string_help_admin_cli_usage 10007
#define kablam_string_err_instance_not_found 10008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
